import Appbar from "@/components/AppBar";
import Providers from "@/components/Providers";
import ModeToggler from "@/components/ui/ModeToggler";

import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ModeToggler />
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
