import Appbar from "@/components/AppBar";
import Providers from "@/components/Providers";
import AppHeader from "@/components/layout/AppHeader";

import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="container">
              <div className="grid grid-rows-[auto,1fr,auto] h-screen">
                <AppHeader />
                <div>{children}</div>
              </div>
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
